sudo: required
dist: trusty

script:
  - echo Creating dir...
  - mkdir build
  - cd build
  - cmake ..
  - make

install:
  #- sudo apt-get update -qq
  #- sudo apt-get install cmake

branches:
  only:
    - master

language: cpp

compiler:
  - gcc

os:
  - linux
  - osx
