sudo: required
dist: trusty

script:
  - echo Creating dir...
  - mkdir build
  - cd build
  - cmake ..
  - make

branches:
  only:
    - master

language: cpp

compiler:
  - gcc

os:
  - linux
  - osx
